### PR TITLE
Feat/community

### PR DESCRIPTION
**Pull request by BenjaSanchez**
1st draft on how this section would look like, @dcsoto if you like the structure of table 1 we can expand it to all other sections

### CODE REVIEW

**Comment by BenjaSanchez** [comment]
@dcsoto I have now changed the column order in tables to "Goal" - "Tool options" - "Additional remarks", to avoid having repeated rows or doing HTML shenanigans. This is how it currently renders:

image

If you like the structure then feel free to implement it in the other sections :)

**Comment by dcsoto** [comment]
Love the latest version of the table! it reads very well :)

**Comment by BenjaSanchez** [comment]
@dcsoto still working on section 3.2 but feel free to start reviewing section 3.1 in the meantime :)

**Review by dcsoto — APPROVED** [review]
All good

**Pull request merged**
