### PR TITLE
Final touches

### PR DESCRIPTION
**Pull request by dcsoto**
Final reviewing the manuscript as a whole before sending to co-authors.

### CODE REVIEW

**Comment by dcsoto** [comment]
I finished reviewing the whole manuscript! Wow, we really wrote a very complete review, in my opinion. I learned a lot from your sections, they are great!

A couple of comments:
- I explained better commits in personal research
- I formatted Table 1 with bold and italics
- I added the word "coverage" in collaboration/test
- I came across the concept of end-to-end testing, do we want to add that?
- I updated the first table in section community, referencing previous tables
- I removed your "to-dos" and tried to address them to the best of my capabilities
- I'm not sure about our supplementary case studies, we could potentially remove them to avoid information overload. What do you think?

After your revision @BenjaSanchez we can share with coauthors :)

**Comment by dcsoto** [comment]
@BenjaSanchez let me know when you have a chance to approve the branch!

Also, I just came across this standard for commits messages: https://www.conventionalcommits.org/en/v1.0.0/

**Review by BenjaSanchez — APPROVED** [review]
@dcsoto great job with this! I directly added some commits, to not delay further. Feel free to change/revert back anything you don't like, otherwise you can go ahead and merge :) Thank you for your patience!

Regarding some of your comments:

> I came across the concept of end-to-end testing, do we want to add that?

Added in collaboration (4th paragraph in "Share code").

> I removed your "to-dos" and tried to addressed them to the best of my capabilities

Thanks for taking care of this, they look great!

> I'm not sure about our supplementary case studies, we could potentially remove them to avoid information overload. What do you think?

It is supplemental material, so I think there's not much harm to leave them... let's see what the other authors say, I'm also fine with deleting them.

> I just came across this standard for commits messages: https://www.conventionalcommits.org/en/v1.0.0/

Added in collaboration (3rd paragraph in "Share code").

Finally, as a side note, I can see some limitations to the manubot approach of writing a manuscript through git, mainly due to git's inability to sometimes properly detect the changes in a long line (in our case, paragraph). For instance:

image

Other tools such as overleaf/google docs/MS word would clearly spot that not every sentence in that paragraph has changed, only a few. So the process of reviewing changes becomes much more tedious. I think this is something we could discuss in the review, what do you think?

**Comment by dcsoto** [comment]
I finally merged the pull request! I tried to track the changes in those long paragraphs (with no highlights), but ultimately gave up! Thanks for the edits, I like the ones that I was able to read! 

Let's move forward sending the document to our respective PIs (former PI in your case). Mine will add comments in the PDF so they can review in parallel. And then submit :) I can take care of that.

**Pull request merged**
